SRC_HOME=/home/fworks/replay/httpConnection/http
g++ -g -m64 -std="c++11" -o main -I. -I${SRC_HOME}/inc -I${SRC_HOME}/protocol -I${SRC_HOME}/util -I${SRC_HOME}/params -I${SRC_HOME}/message ${SRC_HOME}/Main.cc \
                        ${SRC_HOME}/protocol/HTTP.cc \
                        ${SRC_HOME}/HttpHost.cc \
                        ${SRC_HOME}/HttpVersion.cc \
                        ${SRC_HOME}/ProtocolVersion.cc \
                        ${SRC_HOME}/util/CharArrayBuffer.cc \
                        ${SRC_HOME}/util/ByteArrayBuffer.cc \
                        ${SRC_HOME}/params/CoreProtocolPNames.cc \
                        ${SRC_HOME}/params/HttpProtocolParams.cc \
                        ${SRC_HOME}/message/ParserCursor.cc \
                        ${SRC_HOME}/message/BasicHeader.cc \
                        ${SRC_HOME}/message/BasicHeaderValueFormatter.cc \
                        ${SRC_HOME}/message/BasicHeaderValueParser.cc \
                        ${SRC_HOME}/message/BasicHeaderElement.cc \
                        ${SRC_HOME}/message/BasicNameValuePair.cc \
                        ${SRC_HOME}/message/BasicLineFormatter.cc \
                        ${SRC_HOME}/message/BasicRequestLine.cc \
                        ${SRC_HOME}/message/AbstractHttpMessage.cc \
                        ${SRC_HOME}/message/BasicHttpRequest.cc \
                        ${SRC_HOME}/message/HeaderGroup.cc \
                        ${SRC_HOME}/message/BasicListHeaderIterator.cc \
                        ${SRC_HOME}/params/AbstractHttpParams.cc \
                        ${SRC_HOME}/params/BasicHttpParams.cc \
                        ${SRC_HOME}/params/Value.cc \
                        ${SRC_HOME}/message/BasicHeaderIterator.cc \
                        ${SRC_HOME}/message/BasicHeaderElementIterator.cc \
                        ${SRC_HOME}/message/BufferedHeader.cc \
                        ${SRC_HOME}/message/BasicStatusLine.cc \
                        ${SRC_HOME}/message/BasicLineParser.cc -lpthread
